# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FirestoreCli < Formula
  desc "firestore command line interface to work with googles firestore database"
  homepage "https://github.com/Ion-manden/firestore-cli"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.1/firestore-cli_1.1.1_Darwin_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "6649b255642cb3ce49c09962574c5627506422420e4adbae670601b989cfba66"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.1/firestore-cli_1.1.1_Darwin_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "c24c7c6d2ade933c16f79a694725e0ef3f2c0789e006899efb7ed0ae1ffea65c"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.1/firestore-cli_1.1.1_Linux_arm64.tar.gz", :using => CurlDownloadStrategy
      sha256 "f38ab170996a1f20937da273d5c2ab6100e3d59acc1937bbfebb3d3e9c6a0622"

      def install
        bin.install "firestore-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Ion-manden/firestore-cli/releases/download/v1.1.1/firestore-cli_1.1.1_Linux_x86_64.tar.gz", :using => CurlDownloadStrategy
      sha256 "539758a195b174292f3cad54d0cd565ce587db684338a3a9dc4db469a2bb5db6"

      def install
        bin.install "firestore-cli"
      end
    end
  end

  def caveats; <<~EOS
    Refer to README or documentation on the github page
  EOS
  end
end
