name: build-and-release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -o fsctl -v cmd/*.go

    - name: Install GoReleaser
      uses: goreleaser/goreleaser-action@v2
      with:
        install-only: true

    - name: Release
      run: goreleaser release
